version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-iot
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 42418214
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: